### ISSUE TITLE
Daniel Fiore

### ISSUE THREAD

**Issue by 4300df2** [4300df/GradesDF#3]
Can i get a new teacher for first hes so mean to me and he hates me and smacks me burns me etc... Thnaks good bye﻿

**Comment by 4300df** [comment]
Hello Daniel Fiore im sorry your feeling like this maybe you can transfer idk but il do my best to help you

**Comment by 4300df2** [comment]
Hello thanks for responding to me and thanks i really appericate it thanks mr.zumbo﻿

**Comment by 4300df** [comment]
GOOD NEWS WE CAN TRANSFER YOU TO A ANOTHER TEACHER BUT IT WILL BE DONE BUT YOUR GRADES WILL NOT TRANSFER AND BY LOOKING AT THEM THAT MIGHT BE GOOD FOR YOU...
![image](https://user-images.githubusercontent.com/59986880/221331259-2e527890-3165-4363-a049-b2b31b11b01a.png)
